Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/**/*

Metrics/MethodLength:
  Exclude:
    - db/**/*

Metrics/LineLength:
  Max: 120
  Exclude:
    - Gemfile
    - config/**/*

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude: 
    - "bin/**/*"